Update egui and some fixes
LennysLounge/egui_ltreeview pull request #1
Opened 2024-12-19 13:14 UTC by elwerene

2025-01-12 18:14 UTC, obsoleszenz commented
@LennysLounge would need that fix too, would it be possible to get a review?

2025-01-12 18:27 UTC, LennysLounge commented
@elwerene Can you describe that you did in this pr?
I can see that you updated egui to 0.30 but what does "other fixes" mean?

2025-01-12 19:11 UTC, LennysLounge requested changes
The fixes you added don't make a lot of sense to me, mainly because i don't understand the problem the fixes are trying to solve. 

Also please run clippy and fix any deprecation warnings that are shown.

2025-01-12 19:11 UTC, LennysLounge commented on src/builder.rs
> -        }
why?

2025-01-12 19:11 UTC, LennysLounge commented on src/lib.rs
> +#[derive(Clone, Serialize, Deserialize)]
Why does this need to be serializable?

2025-01-12 19:11 UTC, LennysLounge commented on src/lib.rs
> +                if ui.input(|i| i.pointer.button_released(egui::PointerButton::Primary)) {
Why?

2025-01-12 19:11 UTC, LennysLounge commented on src/node.rs
> +            .child_ui(ui.available_rect_before_wrap(), *ui.layout(), None)
`child_ui` is deprecated. Please replace this with the new versions.

2025-01-13 11:30 UTC, elwerene commented
> @elwerene Can you describe that you did in this pr? I can see that you updated egui to 0.30 but what does "other fixes" mean?

Hi, drag and drop was not working for me, maybe a bug which was introduced with the egui update. I will have a look at all your comments and try to fix those later today.

Thanks for taking your time and reviewing my changes!

2025-01-13 20:09 UTC, elwerene commented on examples/playground/main.rs
> +        })
because clippy complained, it was done by `cargo clippy --fix`

2025-01-13 20:13 UTC, elwerene commented on src/lib.rs
> +#[derive(Clone, Serialize, Deserialize)]
it is needed for loading storing the state (https://github.com/LennysLounge/egui_ltreeview/pull/1/files/c3faabd334a4faec0fdc083257a39ec6e41e5d05#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L98). Maybe it was a change to make this requirement explicit in egui, now it is explicit in this library as well.

2025-01-13 20:15 UTC, elwerene commented on src/builder.rs
> -        }
removing this code made drag&drop work for me. It's a long time ago, so I can not give you a deep explenation now. But I just added the code again and then drag/drop did not work anymore

2025-01-13 20:24 UTC, elwerene commented on src/node.rs
> +            .child_ui(ui.available_rect_before_wrap(), *ui.layout(), None)
fixed

2025-01-13 20:25 UTC, elwerene commented on src/lib.rs
> +                if ui.input(|i| i.pointer.button_released(egui::PointerButton::Primary)) {
this was also part of the code which prevented drag/drop from working as far as I can remember. let me test it with your code..

2025-01-13 20:27 UTC, elwerene commented on src/lib.rs
> +                if ui.input(|i| i.pointer.button_released(egui::PointerButton::Primary)) {
nope, maybe I thought that was a problem. I reverted it

2025-01-13 20:28 UTC, elwerene commented
Alright, no clippy warnings left and the code works for me (https://gitlab.com/photonenkollektiv/gled2)

2025-01-13 23:15 UTC, LennysLounge commented on src/lib.rs
> +#[derive(Clone, Serialize, Deserialize)]
Not quite. As i understand it, you only need the serializability if the "persistence" feature of egui is active. This did not change with the version increase. You activated the persistence feature so i was wondering why you did that.

The rust doc on this is also not very good because it only shows the type alias for "SerializableAny" with the serializability. If you look at the source code however this type alias is different depending on if the feature is active or not.

If you really need the persistence feature of egui then this create should also have a feature to turn this on or off. Im happy to add this myself since i have to work out how to do that myself anyway.

2025-01-13 23:25 UTC, LennysLounge commented on src/builder.rs
> -        }
It didn't work in what way? I wouldn't be surprised if the update broke it since the egui update included a bunch of drag and drop changes. But the code was there for a reason. I will look into it if you let me know what you think is broken about it.

2025-01-13 23:26 UTC, LennysLounge requested changes
Yeah happy to merge this once you let me know what is broken about the dragging.

I will then also figure out how to make the persistence feature work properly

2025-01-14 00:17 UTC, elwerene commented on src/lib.rs
> +#[derive(Clone, Serialize, Deserialize)]
I just did it, but could not push the commit yet because of a github outage.

2025-01-14 00:19 UTC, elwerene commented on src/builder.rs
> -        }
If I recall it correctly, at that point the drag already ended, so that conditions always is true and it always returns. This might be because of changes in egui.

2025-01-14 00:21 UTC, elwerene commented on src/lib.rs
> +#[derive(Clone, Serialize, Deserialize)]
it just went through: https://github.com/LennysLounge/egui_ltreeview/pull/1/commits/1278dfeab99084ccb3785de77d035c3897ccfcda

2025-01-14 21:22 UTC, merged

2025-01-14 21:23 UTC, LennysLounge commented
@elwerene Thank you for those changes. I have merged your PR now.

2025-01-14 21:34 UTC, elwerene commented
@LennysLounge Could you please release it on crates.io? It's the only library which stops me from releasing my software on crates.io

2025-01-15 16:00 UTC, elwerene commented
I added an issue for the crates.io release: https://github.com/LennysLounge/egui_ltreeview/issues/2